services:
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - chattyvol:/data/db
    ports:
      - "27017:27017"
  backend:
    container_name: chatty-backend
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  
volumes:
  chattyvol:
