apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 535002880243.dkr.ecr.ap-south-1.amazonaws.com/chatty-frontend:latest
        env:
          - name: VITE_MODE
            value: production
        ports:
        - containerPort: 80